EShopPUA/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EShopPUA.Models;
using System.Data;
using EShopPUA.Helpers;

namespace EShopPUA.Controllers
{
    public class CartsController : Controller
    {
        private readonly DatabaseEShopContext _context;

        public CartsController(DatabaseEShopContext context)
        {
            _context = context;
        }

        //MODELS DEFINITIONS

        public class ClientDataModel
        {
            public string? ClientName { get; set; }
            public string? ClientSurname { get; set; }
            public string? ClientEmail { get; set; }
            public string? ClientPhone { get; set; }
            public string? ClientStreet { get; set; }
            public int? ClientHouseNumber { get; set; }
            public int? ClientApartmentNumber { get; set; } = null;

            public string? ClientCity { get; set; }
            public string? ClientZipCode { get; set; }
            public string? ClientVoivodeship { get; set; }
            public int? PaymentId { get; set; }
        }

        public class OrderViewModel
        {
            public IEnumerable<Category> Categories { get; set; }
            public IEnumerable<CartContentModel> CartContentModels { get; set; }

            public IEnumerable<PaymentMethod> PaymentMethods { get; set; }
            public IEnumerable<Voivodeship> Voivodeships { get; set; }

            public int CartTotal { get; set; }

            public ClientDataModel ClientDataModel { get; set; }

            public string PaymentMethodName { get; set; }
        }

        public class CartViewModel
        {
            public IEnumerable<Category> Categories { get; set; }
            public IEnumerable<CartContentModel> CartContentModels { get; set; }

            public IEnumerable<PaymentMethod> PaymentMethods { get; set; }
            public IEnumerable<Voivodeship> Voivodeships { get; set; }

            public int CartTotal { get; set; }
            //public IEnumerable<Product> Products { get; set; }
            //public IEnumerable<Brand> Brands { get; set; }
        }

        public class CartContentModel
        {
            public Product Product { get; set; }
            public int ProductQuantity { get; set; }
        }

        //ACTIONS
        //Index + ShowVart = cart view
        public async Task<IActionResult> Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
            return View(
                new CartViewModel
                {
                    Categories = await _context.Categories.ToListAsync(),
                    CartContentModels = cart,
                    PaymentMethods = await _context.PaymentMethods.ToListAsync(),
                    Voivodeships = await _context.Voivodeships.ToListAsync(),
                    CartTotal = (int)cart.Sum(item => item.Product.Price * item.ProductQuantity)
                }
            );
        }

        public async Task<IActionResult> ShowCart()
        {
            CartContentModel cartContentModel = new CartContentModel();
            if (SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart") == null)
            {
                List<CartContentModel> cart = new List<CartContentModel>();
                cart.Add(new CartContentModel { Product = await _context.Products.SingleAsync(p => p.Id == 1), ProductQuantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                int index = isExist(1);
                cart.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        //AddToCart - adds to cart or increases the quantity of products
        public async Task<IActionResult> AddToCart(int productId)
        {
            CartContentModel cartContentModel = new CartContentModel();
            if (SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart") == null)
            {
                List<CartContentModel> cart = new List<CartContentModel>();
                cart.Add(new CartContentModel { Product = await _context.Products.SingleAsync(p => p.Id == productId), ProductQuantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<CartContentModel> cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
                int index = isExist(productId);
                if (index != -1)
                {
                    cart[index].ProductQuantity++;
                }
                else
                {
                    cart.Add(new CartContentModel { Product = await _context.Products.SingleAsync(p => p.Id == productId), ProductQuantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        //DecreaseQuantity - removes from cart or decreases the quantity of products
        public async Task<ActionResult> DecreaseQuantity(int productId)
        {
            List<CartContentModel> cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
            int index = isExist(productId);
            if (cart[index].ProductQuantity == 1)
            {
                cart.RemoveAt(index);
            }
            else
            {
                cart[index].ProductQuantity--;
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        //RemoveFromCart - removes from cart
        public IActionResult RemoveFromCart(int productId)
        {
            List<CartContentModel> cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
            int index = isExist(productId);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }


        //Checkout + ShowCheckout = checkout view
        public async Task<IActionResult> Checkout()
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
            return View(
                new CartViewModel
                {
                    Categories = await _context.Categories.ToListAsync(),
                    CartContentModels = cart,
                    PaymentMethods = await _context.PaymentMethods.ToListAsync(),
                    Voivodeships = await _context.Voivodeships.ToListAsync(),
                    CartTotal = (int)cart.Sum(item => item.Product.Price * item.ProductQuantity)
                }
            );
        }

        public async Task<IActionResult> ShowCheckout()
        {
            if (SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart") == null)
            {
                List<CartContentModel> cart = new List<CartContentModel>();
                cart.Add(new CartContentModel { Product = await _context.Products.SingleAsync(p => p.Id == 1), ProductQuantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                int index = isExist(1);
                cart.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return RedirectToAction("Checkout");
            }
            else
            {
                return RedirectToAction("Checkout");
            }
        }

        //OrderPlaced = order summary view
        public async Task<IActionResult> OrderPlaced(ClientDataModel clientDataModel)
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
            var pm = await _context.PaymentMethods.ToListAsync();
            var pmn = pm.Single(p => p.Id == clientDataModel.PaymentId).Name;
            return View(
                new OrderViewModel
                {
                    Categories = await _context.Categories.ToListAsync(),
                    CartContentModels = cart,
                    PaymentMethods = pm,
                    Voivodeships = await _context.Voivodeships.ToListAsync(),
                    CartTotal = (int)cart.Sum(item => item.Product.Price * item.ProductQuantity),
                    ClientDataModel = clientDataModel,
                    PaymentMethodName = pmn
                }
            );
        }
        //CreateOrder = writes the order and client data to DB
        public async Task<IActionResult> CreateOrder(ClientDataModel clientDataModel)
        {
            IEnumerable<Voivodeship> voivodeships = await _context.Voivodeships.ToListAsync();
            List<Client> clients = await _context.Clients.ToListAsync();
            var cart = SessionHelper.GetObjectFromJson<List<CartContentModel>>(HttpContext.Session, "cart");
            int clientId;
            //var clientId = clients.FirstOrDefault(c => c.Email == clientDataModel.ClientEmail).Id;
            if (clients.FirstOrDefault(c => c.Email == clientDataModel.ClientEmail) is null)
            {
                Client client = new Client
                {
                    Name = clientDataModel.ClientName,
                    Surname = clientDataModel.ClientSurname,
                    Email = clientDataModel.ClientEmail,

EShopPUA/Controllers/ShopController.cs
using EShopPUA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EShopPUA.Controllers
{
    //[Authorize]
    public class ShopController : Controller
    {
        private readonly DatabaseEShopContext _context;
        private readonly ILogger<ShopController> _logger;

        public ShopController(ILogger<ShopController> logger, DatabaseEShopContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index(ShopFilters filters, NameFilter nameFilter)
        {
            IEnumerable<Product> products;
            if (filters.SelectedBrands is null || filters.SelectedCategories is null )
            {
                if (nameFilter.ProductName is null)
                {
                    products = await _context.Products.ToListAsync();
                }
                else
                {
                    products = await _context.Products
                        .Where(p => p.Name.Contains(nameFilter.ProductName))
                        .ToListAsync();
                }
                
            }
            else
            {
                products = await _context.Products
                    .Where(p => filters.SelectedBrands.Contains(p.BrandId) && filters.SelectedCategories.Contains(p.CategoryId))
                    .ToListAsync();
            }
            return View(
                new ShopViewModel
                {
                    Categories = await _context.Categories.ToListAsync(),
                    Products = products,
                    Brands = await _context.Brands.ToListAsync(),
                    CountProducts = new CountProducts { Products = await _context.Products.ToListAsync() }
                }
            );
        }

        public async Task<IActionResult> CategoryView(int categoryId)
        {
            IEnumerable<Product> products;
            products = await _context.Products
                    .Where(p => p.CategoryId == categoryId)
                    .ToListAsync();
            return View("~/Views/Shop/Index.cshtml", 
                new ShopViewModel
                {
                    Categories = await _context.Categories.ToListAsync(),
                    Products = products,
                    Brands = await _context.Brands.ToListAsync(),
                    CountProducts = new CountProducts { Products = await _context.Products.ToListAsync() }
                }
            );
        }

        public class ShopFilters
        {
            public IEnumerable<int>? SelectedBrands { get; set; }
            public IEnumerable<int>? SelectedCategories { get; set; }
            public IEnumerable<int>? SelectedPrices { get; set; }

        }

        public class NameFilter
        {
            public string? ProductName { get; set; }
        }

        public class ShopViewModel
        {
            public IEnumerable<Category> Categories { get; set; }
            public IEnumerable<Product> Products { get; set; }
            public IEnumerable<Brand> Brands { get; set; }

            public CountProducts? CountProducts { get; set; }
        }

        public class CountProducts
        {
            public IEnumerable<Product>? Products { get; set; }
            public int TotalProducts
            {
                get
                {
                    return Products.Count();
                }
            }
            public int BrandProducts(int? id)
            {
                return Products.Count(p => p.BrandId == id);
            }

            public int CategoryProducts(int? id)
            {
                return Products.Count(p => p.CategoryId == id);
            }

            public int PriceProducts(int? lowerBound, int? upperBound)
            {
                return Products.Count(p => p.Price >= lowerBound && p.Price <= upperBound);
            }

        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }


}

EShopPUA/Views/Shared/_CategoriesButtons.cshtml
@model IEnumerable<EShopPUA.Models.Category>

<!-- Categories Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        @foreach (var item in Model)
        {
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right"> </p>
                    <a asp-controller="Shop" asp-action="CategoryView" asp-route-categoryId="@item.Id" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/img/categories/@(item.Name).jpg" alt="@item.Name">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">@item.Name</h5>
                </div>
            </div>
        }
    </div>
</div>
<!-- Categories End -->

EShopPUA/Views/Shared/_CategoriesMenu.cshtml
@model IEnumerable<EShopPUA.Models.Category>

<div class="col-lg-3 d-none d-lg-block">
    <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
        <h6 class="m-0">Categories</h6>
        <i class="fa fa-angle-down text-dark"></i>
    </a>
    <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
        <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
            @foreach (var item in Model) {
                <a asp-controller="Shop" asp-action="CategoryView" asp-route-categoryId="@item.Id" class="nav-item nav-link">@item.Name</a>
            }
        </div>
    </nav>
</div>

EShopPUA/Views/Shared/_CategoriesMenuShop.cshtml
@model IEnumerable<EShopPUA.Models.Category>


<div class="col-lg-3 d-none d-lg-block">
    <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
        <h6 class="m-0">Categories</h6>
        <i class="fa fa-angle-down text-dark"></i>
    </a>
    <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
        <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
            @foreach (var item in Model)
            {
                <a asp-controller="Shop" asp-action="CategoryView" asp-route-categoryId="@item.Id" class="nav-item nav-link">@item.Name</a>
            }
        </div>
    </nav>
</div>

EShopPUA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - EShopPUA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EShopPUA.styles.css" asp-append-version="true" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<header>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="https://localhost:7031/swagger">Admin</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>

    </div>
    <!-- Topbar End -->
</header>
<body>
    <!-- Navbar Start -->
    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="" class="text-decoration-none">
                <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Pretty</h1>
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products" name="productName">
                    <div class="input-group-append">
                        <button asp-controller="Shop" asp-action="Index" class="input-group-text bg-transparent text-primary" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            <a href="" class="btn border">
                <i class="fas fa-heart text-primary"></i>
                <span class="badge">0</span>
            </a>
            <a href="" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                <span class="badge">0</span>
            </a>
        </div>
    </div>
    <!-- Navbar End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <!-- Footer Start -->
        <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
            <div class="row px-xl-5 pt-5">
                <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                    <a href="" class="text-decoration-none">
                        <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Pretty</h1>
                    </a>
                    <p>Don't hesitate to contact us at anu inconvinience - we are here to make you feel pretty after all! Please use the contact info listed below:</p>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@epretty.com</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
                <div class="col-lg-8 col-md-12">
                    <div class="row">
                        <div class="col-md-4 mb-5">
                            <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-dark mb-2" asp-controller="Home" asp-action="Index"><i class="fa fa-angle-right mr-2"></i>Home</a>
                                <a class="text-dark mb-2" asp-controller="Shop" asp-action="Index"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                                <a class="text-dark mb-2" asp-controller="Carts" asp-action="ShowCart"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                                <a class="text-dark mb-2" asp-controller="Carts" asp-action="ShowCheckout"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            </div>
                            <div class="d-flex flex-column justify-content-start">
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                            <form action="">
                                <div class="form-group">
                                    <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                           required="required" />
                                </div>
                                <div>
                                    <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row border-top border-light mx-xl-5 py-4">
                <div class="col-md-6 px-xl-0">
                    <p class="mb-md-0 text-center text-md-left text-dark">
                        &copy; <a class="text-dark font-weight-semi-bold" href="#">EPretty</a>. All Rights Reserved. Designed
                        by
                        <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                        Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                    </p>
                </div>
                <div class="col-md-6 px-xl-0 text-center text-md-right">
                    <img class="img-fluid" src="img/payments.png" alt="">
                </div>
            </div>
        </div>
        <!-- Footer End -->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EShopPUA/Views/Shared/_ProductsJustArrived.cshtml
@model IEnumerable<EShopPUA.Models.Product>
@using static EShopPUA.Controllers.CartsController
<!-- Products Start -->

<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Just Arrived</span></h2>
    </div>
    <div class="row px-xl-5 pb-3">

        @foreach (var item in Model.OrderByDescending(d => d.LastModifiedDate).Take(4))
        {
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="card product-item border-0 mb-4">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="img/products/@(item.Name).png" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">@item.Name</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$@(@item.Price)</h6><h6 class="text-muted ml-2">
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a asp-controller="Carts" asp-action="AddToCart" asp-route-productId="@item.Id" class="btn btn-sm text-dark p-0" ><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>
            </div>
        }


    </div>
</div>
<!-- Products End -->

EShopPUA/Views/Shared/_ProductsList.cshtml
@model IEnumerable<EShopPUA.Models.Product>
@using static EShopPUA.Controllers.CartsController

<!-- Shop Product Start -->
<div class="col-lg-9 col-md-12">
    <div class="row pb-3">
        <div class="col-12 pb-1">
            <div class="d-flex align-items-center justify-content-between mb-4">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search by name" name="productName">
                        <div class="input-group-append">
                            <button class="input-group-text bg-transparent text-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        @foreach (var item in Model)
        {
            <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                <div class="card product-item border-0 mb-4">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="~/img/products/@(item.Name).png" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">@item.Name</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$@(@item.Price)</h6><h6 class="text-muted ml-2">
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a asp-controller="Carts" asp-action="AddToCart" asp-route-productId="@item.Id" class="btn btn-sm text-dark p-0" ><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>
            </div>
        }


        <div class="col-12 pb-1">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center mb-3">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<!-- Shop Product End -->
<!-- Products End -->